### ISSUE TITLE
Add asterisks for required fields

### ISSUE THREAD

**Issue by signebedi** [signebedi/libreForms#37]
As name suggests, add red asterisks for required form fields via CSS.

**Comment by signebedi** [comment]
Something like the following, which will require us to mark certain fields as required:

```css
.required::before {
  content: "*";
  color: red; 
}
```
